### PR TITLE
Module 2, Block 2 : Awesome Books: with ES6

### PR DESCRIPTION
**Pull request by aceDavon**
## In this Pull request, I have:

- Used ES6 modules to write modular JavaScript.
- Learned how to use proper ES6 syntax.
- Understood improvements that ES6 brings to JavaScript.
- Display the Time object under the top navigation of the project,
- Made sure that there were no linter errors
- Made sure that I used the correct GitHub Flow on the project.
- Made sure that I documented My work in a professional way.

### CODE REVIEW

**Review by vechicin — CHANGES_REQUESTED** [review]
# Hi @aceDavon ✋, 

Good job so far! 🔥 
There are some issues that you still need to work on to go to the next project but you are almost there! 🚨 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights ⚡ 

- [x] Fantastic UI/UX

## Required Changes ♻️

- [ ] While you did display the time using the `Luxon` library, you didn't structure the files correctly.
Screen Shot 2022-08-08 at 7 35 40
Please make sure you do so.

_Check the comments under the review._

## Optional suggestions 📂 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by aceDavon** [comment]
## Resolved Issues:
- Refactor Time.js to import luxon as a module for use in the file,
- Remove the CDN fetched  time variable and use the imported variable instead

**Review by Reem-lab — APPROVED** [review]
# Hi @aceDavon, 👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉🔥🔥🔥🚀🚀


## Highlights ✨
📌 No Linters error ✅
📌 Great working on the set Up ✅
📌Good working on the requested changes ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by aceDavon** [comment]
> # Hi @aceDavon, 👋🏻👋🏻
> Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: Congratulations! tadafirefirefirerocketrocket  [ 68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f42504a6d74685133595277443651716356442f67697068792e676966 ](https://camo.githubusercontent.com/025552433f3d232fbb4ff2aa99f4018f1ab4d86321c98dbaf6b3d882641805e5/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f42504a6d74685133595277443651716356442f67697068792e676966) [ ](https://camo.githubusercontent.com/025552433f3d232fbb4ff2aa99f4018f1ab4d86321c98dbaf6b3d882641805e5/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f42504a6d74685133595277443651716356442f67697068792e676966)
> 
> ## Highlights 
> pushpin No Linters error white_check_mark pushpin Great working on the set Up white_check_mark pushpinGood working on the requested changes white_check_mark
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
> 
> Cheers and Happy coding!clapclapclap
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

@Reem-lab and @vechicin Thanks so much for your swift responses. I am merging now!

**Comment by aceDavon** [comment]
Project approved and merged

**Pull request merged**
